- set_fact:
    host_os: "{{ ansible_distribution }}"
    host_os_version: "{{ ansible_distribution_major_version }}"

- name: Setup Vagrant file
  template:
    src: Vagrantfile.j2
    dest: Vagrantfile

- name: start vagrant vms
  command: vagrant up --no-provision

- name: provision vagrant vms
  command: vagrant provision
