- name: Setup Vagrant file
  template:
    src: Vagrantfile.j2
    dest: Vagrantfile

- name: start vagrant vms
  command: vagrant up --no-provision

- name: provision vagrant vms
  command: vagrant provision
