- name: create ansible directory (for ssh key)
  file:
    path: /home/vagrant/ansible
    state: directory

- name: copy ssh key
  copy:
    src: /home/vagrant/ansible/vagrant_insecure_private_ssh_key
    dest: /home/vagrant/ansible/vagrant_insecure_private_ssh_key

- name: copy ssh config
  copy:
    src: ssh-config-setup
    dest: /home/vagrant/.ssh/config

- name: copy /etc/hosts
  copy:
    src: etc-hosts
    dest: /etc/hosts
