- name: Check for node connectivity
  block:
    - name: read list of nodes from file cluster_nodes.yml
      include_vars:
        file: cluster-vars.yml

    - name: get hostname
      command: hostname
      register: output

    - name: print hostname
      debug:
        var: output.stdout

    # this is the way gluster-ansible accesses the nodes
    - name: Test ssh to nodes via node address
      command: /bin/true
      delegate_to: "{{ item }}"
      with_items: "{{ gluster_cluster_hosts }}"

- name: Install GlusterFS rpms
  yum:
    name: "{{ gluster_rpms }}"
    state: latest
  vars:
    gluster_rpms:
      - glusterfs-server

- name: Install basic tools
  yum:
   name: "{{ tools }}"
   state: latest
  vars:
    tools:
      - lvm2
      - firewalld
      - libselinux-python

