- name: Add ctdb package
  yum:
    name: ctdb
    state: present

- name: Install python3-libsemanage. This is needed for the seboolean ansible command
  yum: name=python3-libsemanage state=present

- name: SELinux - Allow CTDB to access recovery lockfile from FUSE mount
  seboolean:
    name: use_fusefs_home_dirs
    state: yes
    persistent: yes
