---
- name: Create the ctdb replicated volume
  gluster_volume:
    state: present
    name: "{{ gluster_features_ctdb_volume }}"
    bricks: '{{ ctdb_brick_location }}/ctdb'
    cluster: "{{ gluster_cluster_hosts }}"
    replicas: "{{ gluster_cluster_replica_count }}"
  run_once: yes

- name: Add ctdb package
  yum:
    name: ctdb
    state: present

- name: Add ctdb rules to firewalld
  firewalld:
    service: ctdb
    permanent: yes
    state: enabled

- name: Add recovery lock to ctdb.conf
  lineinfile:
    dest: /etc/ctdb/ctdb.conf
    line: "\trecovery lock = /gluster/lock/recovery.lock"
    regexp: "recovery lock"
    insertafter: '\[cluster\]'

- name: Install libsemanage-python. This is needed for the seboolean ansible command
  yum: name=libsemanage-python state=present

- name: SELinux - Allow CTDB to access recovery lockfile from FUSE mount
  seboolean:
    name: use_fusefs_home_dirs
    state: yes
    persistent: yes

- name: Enable check consistency of databases during startup
  command: '/bin/ctdb event script enable legacy 00.ctdb'

- name: Enable check consistency of databases during startup
  command: '/bin/ctdb event script enable legacy 01.reclock'

- name: Enable monitor system resources
  command: '/bin/ctdb event script enable legacy 05.system'

- name: Enable network interface management by ctdb
  command: '/bin/ctdb event script enable legacy 10.interface'

- name: Enable samba management by ctdb
  command: '/bin/ctdb event script enable legacy 50.samba'

- include_role:
    name: gluster.features

- name: Restart ctdb
  service: name=ctdb state=restarted enabled=yes
