- include_role:
    name: gluster.infra

- name: Enable firewall rules for gluster
  firewalld: service=glusterfs permanent=yes state=enabled

- name: Ensure glusterd service is enabled
  service: name=glusterd state=started enabled=yes

- include_tasks:
    file: "new_volume.yml"
  vars:
    cluster_volume: "{{ replicate_cluster_volume }}"
    cluster_bricks: "{{ replicate_cluster_bricks }}"
    cluster_replica_count: "{{ replicate_cluster_replica_count }}"
    cluster_type: "replicate"
