# -*- mode: ruby -*-
# vi: set ft=ruby :
#

NODES = 2
DISKS = 2
NODE_RAM = 1024
NODE_CPUS = 2
#LIBVIRT_STORAGE_POOL = "data"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.provider :libvirt do |v,override|
        override.vm.box = "centos/7"
        override.vm.synced_folder '.', '/vagrant', disabled: true
        v.qemu_use_session = false
    end

    (0..NODES-1).each do |i|
        config.vm.define "storage#{i}" do |storage|
            storage.vm.hostname = "storage#{i}"
            storage.vm.network :private_network, ip: "192.168.122.10#{i}"
            (0..DISKS-1).each do |d|
                storage.vm.provider :virtualbox do |vb|
                    vb.customize [ "createhd", "--filename", "disk-#{i}#{d}.vdi", "--size", 10*1024 ]
                    vb.customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", 3+d, "--device", 0, "--type", "hdd", "--medium", "disk-#{i}#{d}.vdi" ]
                    vb.memory = NODE_RAM
                    vb.cpus = NODE_CPUS
                end

                driverletters = ('b'..'z').to_a
                storage.vm.provider :libvirt do  |lv|
                    if defined?(LIBVIRT_STORAGE_POOL)
                      lv.storage_pool_name = "#{LIBVIRT_STORAGE_POOL}"
                    end
                    lv.storage :file, :device => "vd#{driverletters[d]}", :path => "disk-#{i}#{d}.disk", :size => '10G'
                    lv.memory = NODE_RAM
                    lv.cpus = NODE_CPUS
                end
            end
        end
    end

    # setup vm:
    # We will runn all our setup playbooks from there.
    config.vm.define "setup" do |setup|
      setup.vm.hostname = "setup"
      # Run a no-op playbook to create the inventory file.
      # Based on that, one can run ansible without vagrant.
      setup.vm.provision "no-op", type:'ansible' do |ansible|
        ansible.playbook = "no-op-playbook.yml"
        ansible.groups = {
          "admin" => [ "setup" ],
          "cluster" => (0..NODES-1).map { |i| "storage#{i}" }
        }
      end
    end
end
