- name: read list of nodes from file cluster_nodes.yml
  include_vars:
    file: cluster-vars.yml

- name: get hostname
  command: hostname
  register: output

- name: print hostname
  debug:
    var: output.stdout

#- name: Test node reachability
#  # note: `net_ping` module does not work unless we put
#  # `ansible_network_os` into the inventory...
#  command: "ping -c 1 {{ item }}"
#  loop:
#    "{{ gluster_cluster_hosts }}"

# this is the way gluster-ansible accesses the nodes
- name: Test ssh to nodes via node address
  command: /bin/true
  delegate_to: "{{ item }}"
  with_items: "{{ gluster_cluster_hosts }}"
