---
- name: Install samba and samba-vfs-glusterfs packages
  yum:
    name:
      - samba
      - samba-vfs-glusterfs
    state: present

- name: Install python3-libsemanage. This is needed for the seboolean ansible command
  yum: name=python3-libsemanage state=present

- name: Selinux - Allow Samba to access glusterfs services
  seboolean:
    name: samba_load_libgfapi
    state: yes
    persistent: yes
