- name: Mount gluster volume using glusterfs
  mount:
    path: /mnt-fuse
    src: "{{ volume }}"
    fstype: glusterfs
    state: mounted

- name: Set permission of volume root to 0777
  file:
    path: /mnt-fuse
    mode: '0777'

- name: Unmount mounted fuse glusterfs mount
  mount:
    path: /mnt-fuse
    state: absent
