---
- name: Install samba and samba-vfs-glusterfs packages
  yum:
    name:
      - samba
      - samba-vfs-glusterfs
    state: present

- name: Enable firewall for samba
  firewalld:
    service: samba
    permanent: yes
    state: enabled

- name: Install libsemanage-python. This is needed for the seboolean ansible command
  yum: name=libsemanage-python state=present

- name: Selinux - Allow Samba to access glusterfs services
  seboolean:
    name: samba_load_libgfapi
    state: yes
    persistent: yes

- name: Create fresh directory /etc/samba/smb.shares to contain share definition
  block:
    - file:
        path: /etc/samba/smb.shares/
        state: absent
    - file:
        path: /etc/samba/smb.shares/
        state: directory
        mode: '0755'

- name: Create smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'

- name: Add share configuration
  block:
    - name: Create share conf file
      template:
        src: smb_share.conf.j2
        dest: "/etc/samba/smb.shares/{{ samba_share }}.conf"
  vars:
    cluster_volume: "{{ gluster_cluster_volume }}"

- name: Include share configuration into smb.conf
  lineinfile:
    path: "/etc/samba/smb.conf"
    line: "include = /etc/samba/smb.shares/{{ samba_share }}.conf"
    insertafter: EOF

- name: Set volume options
  gluster_volume:
    state: present
    name: "{{ gluster_cluster_volume }}"
    options:
      {
        features.cache-invalidation: 'on',
        features.cache-invalidation-timeout: '600',
        performance.cache-samba-metadata: 'on',
        performance.stat-prefetch: 'on',
        performance.cache-invalidation: 'on',
        performance.md-cache-timeout: '600',
        network.inode-lru-limit: '200000',
        performance.nl-cache: 'on',
        performance.nl-cache-timeout: '600',
        performance.readdir-ahead: 'on',
        performance.parallel-readdir: 'on',
      }
  run_once: true

- name: Mount glusterfs using fuse mount and set world writable permissions
  block:
    - name: Mount gluster volume using glusterfs
      mount:
        path: /mnt-fuse
        src: 'localhost:/vol'
        fstype: glusterfs
        state: mounted

    - name: Set permission of share root to 0777
      file:
        path: /mnt-fuse
        mode: '0777'

    - name: Unmount mounted fuse glusterfs mount
      mount:
        path: /mnt-fuse
        state: absent
  run_once: true

- name: Create test users
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid }}"
    state: present
  with_items: "{{ samba_users }}"

- name: Create test users with smbpasswd
  shell: (echo {{ item.password }}; echo {{ item.password }})|smbpasswd -a {{ item.username }}
  with_items: "{{ samba_users }}"
  run_once: yes
