---
- name: Install samba and samba-vfs-glusterfs packages
  yum:
    name:
      - samba
      - samba-vfs-glusterfs
    state: present

- name: Enable firewall for samba
  firewalld:
    service: samba
    permanent: yes
    state: enabled

- name: Install libsemanage-python. This is needed for the seboolean ansible command
  yum: name=libsemanage-python state=present

- name: Selinux - Allow Samba to access glusterfs services
  seboolean:
    name: samba_load_libgfapi
    state: yes
    persistent: yes

- name: Create fresh directory /etc/samba/smb.shares to contain share definition
  block:
    - file:
        path: /etc/samba/smb.shares/
        state: absent
    - file:
        path: /etc/samba/smb.shares/
        state: directory
        mode: '0755'

- name: Create smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'

- name: Add share configuration
  block:
    - name: Create share conf file
      template:
        src: smb_share.conf.j2
        dest: "/etc/samba/smb.shares/{{ samba_share }}.conf"
  vars:
    cluster_volume: "{{ replicated_cluster_volume }}"

- name: Include share configuration into smb.conf
  lineinfile:
    path: "/etc/samba/smb.conf"
    line: "include = /etc/samba/smb.shares/{{ samba_share }}.conf"
    insertafter: EOF

- name: Mount glusterfs using fuse mount and set world writable permissions
  include_tasks:
    file: "fix_share_permissions.yml"
  vars:
    volume: "localhost:/{{ replicated_cluster_volume }}"
  run_once: true

- name: Create test users
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid }}"
    state: present
  with_items: "{{ samba_users }}"

- name: Create test users with smbpasswd
  shell: (echo {{ item.password }}; echo {{ item.password }})|smbpasswd -a {{ item.username }}
  with_items: "{{ samba_users }}"
  run_once: yes
