- name: git hash
  command: git log -1 --format=%h
  args:
    chdir: "{{ code_dir }}"
  register: githashcmd

- set_fact:
    githash: "{{ githashcmd.stdout }}"

- name: git date
  # older git (on centos7) don't support --date=format: ...
  #command: git log -1 --format=format:%cd --date=format:'%Y%m%d.%H%M%S'
  command: git log -1 --format=format:%cd --date=iso
  args:
    chdir: "{{ code_dir }}"
  register: gitdatecmd

- set_fact:
    # with --date=format:, the regex_replace filters would not be needed
    gitdate: "{{ gitdatecmd.stdout | regex_replace('-', '') | regex_replace(' [^ ]*$', '') | regex_replace('\\:', '') | regex_replace(' ', '.') }}"

- set_fact:
    samba_rpm_version: "{{ gitdate + '.' + githash if ('master' in gitbranch.stdout) else release_version.stdout + '.' + gitdate + '.' + githash }}"

- set_fact:
    samba_prefix: "samba-{{ samba_rpm_version }}"

- set_fact:
    samba_tarball: "{{ spec_dir}}/{{ samba_prefix }}.tar.gz"

# `make dist` would be the preferred way of creating the tarball
# but it uses the version generated from the VERSION file which
# is not suitable for rpm building if we add the vendor suffix.
# Therefore using `git archive` (for now)...
#
- name: make tarball
  command: git archive --prefix={{ samba_prefix }}/ --output={{ samba_tarball }} HEAD
  args:
    chdir: "{{ code_dir }}"
