- name: Enable EPEL repository
  yum:
    name: epel-release
    state: latest

- name: Enable gluster-ansible copr from sac
  command: yum-config-manager --add-repo https://copr.fedorainfracloud.org/coprs/sac/gluster-ansible/repo/epel-7/sac-gluster-ansible-epel-7.repo

- name: Install gluster-ansible
  yum:
    name: "gluster-ansible"
    state: latest

- name: copy ansible playbooks to setup machine
  synchronize:
    src: ansible/
    dest: /home/vagrant/ansible

- name: ensure permissions on ssh key file
  file:
    path: /home/vagrant/ansible/vagrant_insecure_private_ssh_key
    mode: u=rw,g=,o=

- name: copy ssh config in place
  copy:
   src: ansible/ssh-config-setup
   dest: /home/vagrant/.ssh/config
